apiVersion: v1
kind: Pod
metadata:
   name: machineinfo
spec:
   containers:
   - name: machineinfo-container01
     image: deepakbedase/machineinfo_env:v1.1.0
      env:
    - name: test-secret
      valueFrom:
        secretKeyRef:
          name: mycolor
          key: color
     ports:
     - containerPort: 9000
       hostPort: 9000
