--- 
apiVersion: v1
kind: Pod
metadata: 
  name: machineinfo
spec: 
  containers: 
    - 
      env: 
        - 
          name: test-secret
          secretKeyRef: 
            key: color
            name: mycolor
          valueFrom: ~
      image: "deepakbedase/machineinfo_env:v1.1.0"
      name: machineinfo-container01
      ports: 
        - 
          containerPort: 9000
          hostPort: 9000
