apiVersion: v1
kind: Pod
metadata:
   name: machineinfo
spec:
   containers:
   - name: machineinfo-container01
     image: deepakbedase/machineinfo_env:v1.1.0
     envFrom:
        - configMapRef:
            name: colorconfig
     ports:
     - containerPort: 9000
       hostPort: 9000
