--- 
apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: machineinfo
    name: machineinfo
  name: MI-service
spec: 
  selector: 
    app: machineinfo
    ports: 
      - 
        nodePort: 31000
        port: 9000
        targetPort: 9000
    type: NodePort
